const images = {
  teams: require('./teams.jpg'),
  vettel: require('./vettel.jpg'),
  finish: require('./finish.jpg'),
  logo: require('./f1_logo.svg'),
  teams2018: {
    mercedes: require('./teams/mercedes.png'),
    ferrari: require('./teams/ferrari.png'),
    red_bull: require('./teams/red_bull.png'),
    renault: require('./teams/renault.png'),
    force_india: require('./teams/force_india.png'),
    haas: require('./teams/haas.png'),
    mclaren: require('./teams/mclaren.png'),
    toro_rosso: require('./teams/toro_rosso.png'),
    sauber: require('./teams/sauber.png'),
    williams: require('./teams/williams.png'),
  },
  drivers2018: {
    alonso: require('./drivers/alonso.png'),
    bottas: require('./drivers/bottas.png'),
    brendon_hartley: require('./drivers/brendon_hartley.png'),
    ericsson: require('./drivers/ericsson.png'),
    gasly: require('./drivers/gasly.png'),
    grosjean: require('./drivers/grosjean.png'),
    hamilton: require('./drivers/hamilton.png'),
    hulkenberg: require('./drivers/hulkenberg.png'),
    kevin_magnussen: require('./drivers/kevin_magnussen.png'),
    leclerc: require('./drivers/leclerc.png'),
    max_verstappen: require('./drivers/max_verstappen.png'),
    ocon: require('./drivers/ocon.png'),
    perez: require('./drivers/perez.png'),
    raikkonen: require('./drivers/raikkonen.png'),
    ricciardo: require('./drivers/ricciardo.png'),
    sainz: require('./drivers/sainz.png'),
    sirotkin: require('./drivers/sirotkin.png'),
    stroll: require('./drivers/stroll.png'),
    vandoorne: require('./drivers/vandoorne.png'),
    vettel: require('./drivers/vettel.png'),
  }
};

export default images;